include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: seeeduino_xiao_ble
    shield: totem_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# Add custom dongle and a peripheral left corne
  - board: seeeduino_xiao_ble
    shield: totem_dongle

  - board: seeeduino_xiao_ble
    shield: settings_reset

# there is no settingsreset (needed) for the XIAO
