include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: seeeduino_xiao_ble
    shield: totem_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

# Add custom dongle and enable ZMK Studio
  - board: seeeduino_xiao_ble
    shield: totem_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: seeeduino_xiao_ble
    shield: settings_reset

# there is no settingsreset (needed) for the XIAO
